
//USER

export const LOGON = 'LOGON';
export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';


export const USER_HOME_NEW = 'USER_HOME_NEW';
export const USER_SALAS_NEW = 'USER_SALAS_NEW';
export const USER_DUO_NEW = 'USER_DUO_NEW';

export const USER_MODAL= 'USER_MODAL';
export const USER_HELP= 'USER_HELP';


export const VER_ACTIVITY= 'VER_ACTIVITY';
export const VER_SALA_FILTRO= 'VER_SALA_FILTRO';

export const DESARROLLO_INCREMENT = 'DESARROLLO_INCREMENT';
export const DESARROLLO_DECREMENT = 'DESARROLLO_DECREMENT';

export const ENVIO_VIEW= 'ENVIO_VIEW';


export const OBJECION_SAVE = 'OBJECION_SAVE';
export const OBJECION_DELETE = 'OBJECION_DELETE';
export const OBJECION_SEND = 'OBJECION_SEND';

export const USER_GET_SALA_OK = 'USER_GET_SALA_OK';
export const USER_GET_SALA_REQUEST = 'USER_GET_SALA_REQUEST';
export const USER_GET_SALA_ERROR = 'USER_GET_SALA_ERROR';


//SALAS



export const SALAS_CONTAR_VISTA= 'SALAS_CONTAR_VISTA';
export const SALAS_VISTA = 'SALAS_VISTA';

export const SALAS_ORDEN_KEYS= 'SALAS_ORDEN_KEYS';
export const SALAS_ORDEN_ASC= 'SALAS_ORDEN_ASC';

export const SALA_DETALLES_VIEW= 'SALA_DETALLES_VIEW';
export const SALA_DETALLES_GUARDA_DATA= 'SALA_DETALLES_GUARDA_DATA';


//TAREAS


export const TAREA_CONTAR_VISTA= 'TAREA_CONTAR_VISTA';
export const TAREA_VISTA = 'TAREA_VISTA';


export const GET_TAREA_OK = 'GET_SALA_OK';
export const GET_TAREA_REQUEST = 'GET_SALA_REQUEST';
export const GET_TAREA_ERROR = 'GET_SALA_ERROR';

export const TAREA_ORDEN_KEYS= 'TAREA_ORDEN_KEYS';
export const TAREA_ORDEN_ASC= 'TAREA_ORDEN_ASC';

export const TAREA_DETALLES_VIEW= 'TAREA_DETALLES_VIEW';
export const TAREA_DETALLES_GUARDA_DATA= 'TAREA_DETALLES_GUARDA_DATA';